/**
 * ******************************************************************************************
 * Copyright (C) 2012 - Food and Agriculture Organization of the United Nations (FAO).
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice,this list
 *       of conditions and the following disclaimer.
 *    2. Redistributions in binary form must reproduce the above copyright notice,this list
 *       of conditions and the following disclaimer in the documentation and/or other
 *       materials provided with the distribution.
 *    3. Neither the name of FAO nor the names of its contributors may be used to endorse or
 *       promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,STRICT LIABILITY,OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * *********************************************************************************************
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrintForm.java
 *
 * Created on Dec 20, 2011, 4:57:31 PM
 */
package org.geotools.swing.mapaction.extended.ui;

import java.awt.ComponentOrientation;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import org.geotools.swing.extended.util.Messaging;
import org.geotools.swing.mapaction.extended.print.PrintLayout;

/**
 * A form used during the print operation to define some parameters before printing.
 * 
 * @author Elton Manoku
 */
public class PrintForm extends javax.swing.JDialog implements IPrintUi{

    private boolean continueWithPrinting = false;
    private PrintLayout printLayout;
    private List<PrintLayout> printLayoutList;
    private Integer scale = null;
    private Object txtFont = "TextField.font";
    private Object btnFont = "Button.font";
    private Object cmbFont = "ComboBox.font";
    private Object labFont = "Label.font";
    

    public PrintForm() {
        initComponents();
        java.util.ResourceBundle bundleTitle = java.util.ResourceBundle.getBundle("org/geotools/swing/mapaction/extended/ui/Bundle"); // NOI18N
        this.setTitle((bundleTitle.getString("PrintForm.title.text")));
        this.setAlwaysOnTop(true);
        this.setModalityType(ModalityType.APPLICATION_MODAL);
    }

    @Override
    public Integer getScale() {
        return scale;
    }

    @Override
    public void setScale(Integer scale) {
        this.scale = scale;
        this.txtScale.setText(this.scale.toString());
    }

    @Override
    public PrintLayout getPrintLayout() {
        return printLayout;
    }

    public List<PrintLayout> getPrintLayoutList() {
        return printLayoutList;
    }

    @Override
    public void setPrintLayoutList(List<PrintLayout> printLayoutList) {
        this.printLayoutList = printLayoutList;
        this.cmdLayout.removeAllItems();
        for (PrintLayout layout : this.printLayoutList) {
            this.cmdLayout.addItem(layout);
        }
    }

    @Override
    public void setVisibility(boolean visible){
        this.setVisible(visible);
    }
    
    @Override
    public java.util.Map<String, Object> getExtraFields(){
        return new HashMap<String, Object>();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdLayout = new javax.swing.JComboBox();
        cmdPrint = new javax.swing.JButton();
        lblCmdLayout = new javax.swing.JLabel();
        txtScale = new javax.swing.JTextField();
        lblTxtScale = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        cmdLayout.setFont(UIManager.getFont(cmbFont));
        cmdLayout.setComponentOrientation(ComponentOrientation.getOrientation(Locale.getDefault()));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/geotools/swing/mapaction/extended/ui/Bundle"); // NOI18N
        cmdPrint.setText(bundle.getString("PrintForm.cmdPrint.text")); // NOI18N
        cmdPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrintActionPerformed(evt);
            }
        });
        cmdPrint.setFont(UIManager.getFont(btnFont));
        cmdPrint.setComponentOrientation(ComponentOrientation.getOrientation(Locale.getDefault()));
        cmdPrint.setHorizontalAlignment(JButton.CENTER);

        lblCmdLayout.setText(bundle.getString("PrintForm.lblCmdLayout.text")); // NOI18N
        lblCmdLayout.setFont(UIManager.getFont(labFont));
        lblCmdLayout.setComponentOrientation(ComponentOrientation.getOrientation(Locale.getDefault()));
        lblCmdLayout.setHorizontalAlignment(JLabel.LEADING);

        txtScale.setText(bundle.getString("PrintForm.txtScale.text")); // NOI18N
        txtScale.setFont(UIManager.getFont(txtFont));
        txtScale.setComponentOrientation(ComponentOrientation.getOrientation(Locale.getDefault()));
        txtScale.setHorizontalAlignment(JTextField.LEADING);

        lblTxtScale.setText(bundle.getString("PrintForm.lblTxtScale.text")); // NOI18N
        lblTxtScale.setFont(UIManager.getFont(labFont));
        lblTxtScale.setComponentOrientation(ComponentOrientation.getOrientation(Locale.getDefault()));
        lblTxtScale.setHorizontalAlignment(JLabel.LEADING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdPrint, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTxtScale)
                            .addComponent(lblCmdLayout))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtScale, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCmdLayout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTxtScale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(cmdPrint)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmdPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrintActionPerformed

    if (this.cmdLayout.getSelectedItem() == null) {
        Messaging.getInstance().show(Messaging.Ids.PRINT_LAYOUT_NOT_SELECTED.toString());
    } else {
        this.printLayout = (PrintLayout) this.cmdLayout.getSelectedItem();
        try {
            this.scale = Integer.parseInt(this.txtScale.getText());
            this.continueWithPrinting = true;
            this.setVisible(false);
        } catch (NumberFormatException ex) {
            Messaging.getInstance().show(Messaging.Ids.PRINT_SCALE_NOT_CORRECT.toString());
        }
    }

}//GEN-LAST:event_cmdPrintActionPerformed

private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
this.continueWithPrinting = false;
}//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmdLayout;
    private javax.swing.JButton cmdPrint;
    private javax.swing.JLabel lblCmdLayout;
    private javax.swing.JLabel lblTxtScale;
    private javax.swing.JTextField txtScale;
    // End of variables declaration//GEN-END:variables
}
