/*
 * Copyright 2013 Food and Agriculture Organization of the United Nations (FAO).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sola.clients.swing.admin.system;

import org.sola.clients.swing.common.tasks.SolaTask;
import static org.sola.clients.swing.common.tasks.SolaTask.TASK_DONE;
import static org.sola.clients.swing.common.tasks.SolaTask.TASK_PENDING;
import org.sola.clients.swing.common.tasks.TaskManager;
import org.sola.clients.swing.ui.ContentPanel;
import org.sola.common.FileUtility;
import org.sola.common.messaging.ClientMessage;
import org.sola.common.messaging.MessageUtility;
import org.sola.services.boundary.wsclients.WSManager;

/**
 *
 * @author Elton Manoku
 */
public class ConsolidationExtractPanel extends ContentPanel {

    public static final String PANEL_NAME = "ConsolidationExtractPanel";
    /**
     * Creates new form ConsolidationExtractPanel
     */
    public ConsolidationExtractPanel() {
        initComponents();
    }

    private void run(){
        SolaTask t = new SolaTask<Void, Void>() {
            
            //The file name in the documents folder in the client.
            String fileOfExtract = "";

            @Override
            public Void doTask() {
                lblLabelInformation.setText("");
                setMessage(MessageUtility.getLocalizedMessageText(
                        ClientMessage.ADMIN_CONSOLIDATION_EXTRACT));
                fileOfExtract = WSManager.getInstance().getAdminService().consolidationExtract();
                WSManager.getInstance().getFileStreamingService().download(fileOfExtract, fileOfExtract);
                return null;
            }

            @Override
            protected void taskDone() {
                super.taskDone();
                lblLabelInformation.setText(MessageUtility.getLocalizedMessage(
                        ClientMessage.ADMIN_CONSOLIDATION_EXTRACT_OUTPUT_FILE, 
                        new String[]{ FileUtility.getCachePath() + fileOfExtract}).getMessage());
            }
        };
        TaskManager.getInstance().runTask(t);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new org.sola.clients.swing.ui.HeaderPanel();
        btnStart = new javax.swing.JButton();
        lblLabelInformation = new javax.swing.JLabel();

        setHeaderPanel(pnlHeader);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/sola/clients/swing/admin/system/Bundle"); // NOI18N
        pnlHeader.setTitleText(bundle.getString("ConsolidationExtractPanel.pnlHeader.titleText")); // NOI18N

        btnStart.setText(bundle.getString("ConsolidationExtractPanel.btnStart.text")); // NOI18N
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        lblLabelInformation.setText(bundle.getString("ConsolidationExtractPanel.lblLabelInformation.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblLabelInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLabelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        run();
    }//GEN-LAST:event_btnStartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblLabelInformation;
    private org.sola.clients.swing.ui.HeaderPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
