/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sola.clients.swing.gis.ui.control;

import java.util.HashMap;
import java.util.List;
import org.geotools.swing.extended.util.Messaging;
import org.geotools.swing.mapaction.extended.print.PrintLayout;
import org.geotools.swing.mapaction.extended.ui.IPrintUi;

/**
 *
 * @author Elton Manoku
 */
public class PublicDisplayPrintForm extends javax.swing.JDialog implements IPrintUi {

    private boolean continueWithPrinting = false;
    private List<PrintLayout> printLayoutList;
    private Integer scale = null;
    private PrintLayout printLayout;

    /**
     * Creates new form PublicDisplayPrintForm
     */
    public PublicDisplayPrintForm() {
        initComponents();
        this.setAlwaysOnTop(true);
        this.setModalityType(ModalityType.APPLICATION_MODAL);
    }

    @Override
    public Integer getScale() {
        return scale;
    }

    @Override
    public void setScale(Integer scale) {
        this.scale = scale;
        this.txtScale.setText(this.scale.toString());
    }

    @Override
    public PrintLayout getPrintLayout() {
        return printLayout;
    }

    @Override
    public void setPrintLayoutList(List<PrintLayout> printLayoutList) {

        this.printLayoutList = printLayoutList;
        this.cmbLayoutList.removeAllItems();
        for (PrintLayout layout : this.printLayoutList) {
            this.cmbLayoutList.addItem(layout);
        }
    }

    @Override
    public void setVisibility(boolean visible) {
        this.setVisible(visible);
    }

    @Override
    public java.util.Map<String, Object> getExtraFields() {
        return new HashMap<String, Object>();
    }
    
    public String getAreaDescription(){
        return this.txtArea.getText()!=null?this.txtArea.getText():"";
    } 
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        cmbLayoutList = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtScale = new javax.swing.JTextField();
        cmdPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/sola/clients/swing/gis/ui/control/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("PublicDisplayPrintForm.jLabel1.text")); // NOI18N

        txtArea.setText(bundle.getString("PublicDisplayPrintForm.txtArea.text")); // NOI18N

        cmbLayoutList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText(bundle.getString("PublicDisplayPrintForm.jLabel2.text")); // NOI18N

        jLabel3.setText(bundle.getString("PublicDisplayPrintForm.jLabel3.text")); // NOI18N

        txtScale.setText(bundle.getString("PublicDisplayPrintForm.txtScale.text")); // NOI18N

        cmdPrint.setText(bundle.getString("PublicDisplayPrintForm.cmdPrint.text")); // NOI18N
        cmdPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtScale, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtArea)
                                .addComponent(cmbLayoutList, 0, 200, Short.MAX_VALUE))))
                    .addComponent(cmdPrint, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLayoutList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(cmdPrint)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrintActionPerformed
            if (this.cmbLayoutList.getSelectedItem() == null) {
        Messaging.getInstance().show(Messaging.Ids.PRINT_LAYOUT_NOT_SELECTED.toString());
    } else {
        this.printLayout = (PrintLayout) this.cmbLayoutList.getSelectedItem();
        try {
            this.scale = Integer.parseInt(this.txtScale.getText());
            this.continueWithPrinting = true;
            this.setVisible(false);
        } catch (NumberFormatException ex) {
            Messaging.getInstance().show(Messaging.Ids.PRINT_SCALE_NOT_CORRECT.toString());
        }
    }

    }//GEN-LAST:event_cmdPrintActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        this.continueWithPrinting = false;
    }//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbLayoutList;
    private javax.swing.JButton cmdPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtScale;
    // End of variables declaration//GEN-END:variables
}
