/**
 * ******************************************************************************************
 * Copyright (C) 2014 - Food and Agriculture Organization of the United Nations
 * (FAO). All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,this
 * list of conditions and the following disclaimer. 2. Redistributions in binary
 * form must reproduce the above copyright notice,this list of conditions and
 * the following disclaimer in the documentation and/or other materials provided
 * with the distribution. 3. Neither the name of FAO nor the names of its
 * contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT,STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * *********************************************************************************************
 */
package org.sola.clients.swing.desktop.administrative;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import org.sola.clients.beans.administrative.BaUnitSearchResultBean;
import org.sola.clients.beans.administrative.BaUnitSummaryBean;
import org.sola.clients.beans.administrative.ValuationBean;
import org.sola.clients.beans.administrative.ValuationListBean;
import org.sola.clients.beans.application.ApplicationBean;
import org.sola.clients.beans.application.ApplicationServiceBean;
import org.sola.clients.beans.security.SecurityBean;
import org.sola.clients.swing.common.tasks.SolaTask;
import org.sola.clients.swing.common.tasks.TaskManager;
import org.sola.clients.swing.desktop.MainForm;
import org.sola.clients.swing.ui.ContentPanel;
import org.sola.clients.swing.ui.MainContentPanel;
import org.sola.common.RolesConstants;
import org.sola.common.messaging.ClientMessage;
import org.sola.common.messaging.MessageUtility;

/**
 *
 * @author Troy
 */
public class ValuationListPanel extends ContentPanel {

    /**
     * Creates new form ValuationListPanel
     *
     * @param applicationBean
     * @param applicationService
     * @param readOnly
     */
    public ValuationListPanel(ApplicationBean applicationBean,
            ApplicationServiceBean applicationService,
            Boolean readOnly) {
        this.readOnly = readOnly || !SecurityBean.isInRole(RolesConstants.APPLICATION_EDIT_APPS);
        this.applicationBean = applicationBean;
        this.applicationService = applicationService;
        initComponents();
        customizeForm();

        listBean.addPropertyChangeListener(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (evt.getPropertyName().equals(ValuationListBean.SELECTED_VALUATION_ITEM)) {
                    customizeButtons((ValuationBean) evt.getNewValue());
                }
            }
        });

        saveListBeanState();

    }

    public ValuationListPanel() {
        initComponents();
    }

    @Override
    protected boolean panelClosing() {
        tblValuations.clearSelection();
        if (btnSave.isEnabled() && MainForm.checkSaveBeforeClose(listBean)) {
            return saveValuationList(true);
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listBean = initValuationListBean(applicationService.getId());
        headerPanel1 = new org.sola.clients.swing.ui.HeaderPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnSave = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblValuations = new org.sola.clients.swing.common.controls.JTableWithDefaultStyles();

        setHeaderPanel(headerPanel1);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/sola/clients/swing/desktop/administrative/Bundle"); // NOI18N
        headerPanel1.setTitleText(bundle.getString("ValuationListPanel.headerPanel1.titleText")); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName(""); // NOI18N

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/common/save.png"))); // NOI18N
        btnSave.setText(bundle.getString("ValuationListPanel.btnSave.text")); // NOI18N
        btnSave.setFocusable(false);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/common/view.png"))); // NOI18N
        btnView.setText(bundle.getString("ValuationListPanel.btnView.text")); // NOI18N
        btnView.setFocusable(false);
        btnView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnView);
        jToolBar1.add(jSeparator1);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/common/add.png"))); // NOI18N
        btnAdd.setText(bundle.getString("ValuationListPanel.btnAdd.text")); // NOI18N
        btnAdd.setFocusable(false);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdd);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/common/folder-open-document-text.png"))); // NOI18N
        btnEdit.setText(bundle.getString("ValuationListPanel.btnEdit.text")); // NOI18N
        btnEdit.setFocusable(false);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEdit);

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/common/remove.png"))); // NOI18N
        btnRemove.setText(bundle.getString("ValuationListPanel.btnRemove.text")); // NOI18N
        btnRemove.setFocusable(false);
        btnRemove.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRemove);

        tblValuations.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${valuationList}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listBean, eLProperty, tblValuations);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nr}"));
        columnBinding.setColumnName("Nr");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${baUnitBasic.displayName}"));
        columnBinding.setColumnName("Ba Unit Basic.display Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${baUnitBasic.area}"));
        columnBinding.setColumnName("Ba Unit Basic.area");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${amount}"));
        columnBinding.setColumnName("Amount");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${type.displayValue}"));
        columnBinding.setColumnName("Type.display Value");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${description}"));
        columnBinding.setColumnName("Description");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listBean, org.jdesktop.beansbinding.ELProperty.create("${selectedValuation}"), tblValuations, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        tblValuations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblValuationsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblValuations);
        if (tblValuations.getColumnModel().getColumnCount() > 0) {
            tblValuations.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("ValuationListPanel.tblValuations.columnModel.title0_1")); // NOI18N
            tblValuations.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("ValuationListPanel.tblValuations.columnModel.title1_1")); // NOI18N
            tblValuations.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("ValuationListPanel.tblValuations.columnModel.title2_1")); // NOI18N
            tblValuations.getColumnModel().getColumn(2).setCellRenderer( new org.sola.clients.swing.ui.renderers.AreaCellRenderer());
            tblValuations.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("ValuationListPanel.tblValuations.columnModel.title3_1")); // NOI18N
            tblValuations.getColumnModel().getColumn(3).setCellRenderer(new org.sola.clients.swing.ui.renderers.MoneyCellRenderer());
            tblValuations.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("ValuationListPanel.tblValuations.columnModel.title4_1")); // NOI18N
            tblValuations.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("ValuationListPanel.tblValuations.columnModel.title5")); // NOI18N
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveValuationList(true);
        btnSave.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addValuation(new ValuationBean(), false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        if (listBean.getSelectedValuation() != null) {
            openValuation(listBean.getSelectedValuation(), true);
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (listBean.getSelectedValuation() != null) {
            openValuation(listBean.getSelectedValuation(), readOnly);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        removeValuation(listBean.getSelectedValuation());
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void tblValuationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblValuationsMouseClicked
        if (evt.getClickCount() == 2) {
            if (btnEdit.isEnabled()) {
                openValuation(listBean.getSelectedValuation(), readOnly);
            } else if (btnView.isEnabled()) {
                openValuation(listBean.getSelectedValuation(), true);
            }
        }
    }//GEN-LAST:event_tblValuationsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnView;
    private org.sola.clients.swing.ui.HeaderPanel headerPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private org.sola.clients.beans.administrative.ValuationListBean listBean;
    private org.sola.clients.swing.common.controls.JTableWithDefaultStyles tblValuations;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void addValuation(final ValuationBean valuation, final boolean viewItem) {
        SolaTask t = new SolaTask<Void, Void>() {
            @Override
            public Void doTask() {
                setMessage(MessageUtility.getLocalizedMessageText(ClientMessage.PROGRESS_MSG_OPEN_PROPERTYSEARCH));
                BaUnitSearchPanel propSearchPanel = new BaUnitSearchPanel(applicationBean);
                // Configure the panel for display
                propSearchPanel.getSearchPanel().showSelectButtons(true);
                propSearchPanel.getSearchPanel().showOpenButtons(true);
                propSearchPanel.getSearchPanel().setDefaultActionOpen(false);
                propSearchPanel.setCloseOnSelect(true);
                propSearchPanel.addPropertyChangeListener(new PropertyChangeListener() {
                    @Override
                    public void propertyChange(PropertyChangeEvent evt) {
                        if (evt.getPropertyName().equals(BaUnitSearchPanel.SELECTED_RESULT_PROPERTY)) {
                            BaUnitSearchResultBean bean = (BaUnitSearchResultBean) evt.getNewValue();
                            if (bean != null) {
                                BaUnitSummaryBean prop = new BaUnitSummaryBean(bean);
                                valuation.setBaUnitId(bean.getId());
                                valuation.setSelectedProperty(prop);
                                valuation.setBaUnitBasic(prop);
                                openValuation(valuation, viewItem);
                            }
                        }
                    }
                });
                getMainContentPanel().addPanel(propSearchPanel, MainContentPanel.CARD_BAUNIT_SEARCH, true);
                return null;
            }
        };
        TaskManager.getInstance().runTask(t);
    }

    private void customizeForm() {
        // Disable the edit buttons if the form is in read only mode
        btnSave.setEnabled(false);
        btnAdd.setEnabled(!readOnly);
        customizeButtons(null);
    }

    private void customizeButtons(ValuationBean item) {
        boolean enable = item != null && !readOnly;
        btnView.setEnabled(item != null);
        btnEdit.setEnabled(enable);
        btnRemove.setEnabled(enable);
    }

    private void saveListBeanState() {
        tblValuations.clearSelection();
        MainForm.saveBeanState(listBean);
    }

    private boolean saveValuationList(final boolean showMessage) {
        final boolean[] result = {listBean.validate(true).size() < 1};
        if (result[0]) {
            // Save the checklist items
            SolaTask<Void, Void> t = new SolaTask<Void, Void>() {
                @Override
                public Void doTask() {
                    setMessage(MessageUtility.getLocalizedMessageText(ClientMessage.PROGRESS_MSG_SAVING));
                    listBean.saveList();
                    return null;
                }

                @Override
                public void taskDone() {
                    saveListBeanState();
                    if (showMessage) {
                        // Only display the Saved message if the user has choosen to explicitly save
                        MessageUtility.displayMessage(ClientMessage.VALUATION_SUCCESSFULLY_SAVED);
                    }
                }

                @Override
                protected void taskFailed(Throwable e) {
                    // If the fail saves due to a database or connection exception, 
                    // capture the result for the save. 
                    result[0] = false;
                    super.taskFailed(e);
                }
            };
            TaskManager.getInstance().runTask(t);
        }
        return result[0];
    }

    private void openValuation(final ValuationBean valuation,
            final boolean viewItem) {

        SolaTask t = new SolaTask<Void, Void>() {
            @Override
            public Void doTask() {
                ValuationBean obj = null;
                if (valuation != null) {
                    boolean hasChanges = MainForm.checkBeanState(listBean);
                    // Create a copy of the objection so that if the user decides to cancel thier changes
                    // the data on the original objection is unchanged. 
                    obj = valuation.copy();
                    if (!hasChanges) {
                        // The copy will change the state of the listBean, so reset the bean state
                        // if no changes had been made. 
                        saveListBeanState();
                    }
                }

                setMessage(MessageUtility.getLocalizedMessageText(ClientMessage.PROGRESS_MSG_OPEN_VALUATION));
                ValuationPanel panel = new ValuationPanel(obj, applicationBean, applicationService, viewItem, false);
                panel.addPropertyChangeListener(new PropertyChangeListener() {

                    @Override
                    public void propertyChange(PropertyChangeEvent evt) {
                        if (evt.getPropertyName().equals(ValuationPanel.VALUATION_SAVED)) {
                            listBean.addOrUpdateItem((ValuationBean) evt.getNewValue());
                            tblValuations.clearSelection();
                            btnSave.setEnabled(true);
                        }
                    }
                });
                getMainContentPanel().addPanel(panel, MainContentPanel.CARD_VALUATION_PANEL, true);
                return null;
            }
        };
        TaskManager.getInstance().runTask(t);
    }

    private void removeValuation(ValuationBean item) {
        if (item != null) {
            listBean.removeItem(item);
        }
    }

    /**
     * Initializes a new ValuationListBean with default values.
     *
     * @return
     */
    private ValuationListBean initValuationListBean(String serviceId) {
        ValuationListBean valuationListBean = new ValuationListBean();
        valuationListBean.loadList(serviceId);
        return valuationListBean;
    }

    private boolean readOnly = false;
    private ApplicationBean applicationBean;
    private ApplicationServiceBean applicationService;
}
